// Main schema file - exports all tables from both schemas

// Platform schema (global SaaS configuration)
export {
  platformSchema,
  emails,
  tenantPlans,
  admins,
  emailsRelations,
  adminsRelations,
  tenantPlansRelations,
} from "./schema-platform";

export type {
  Email,
  NewEmail,
  TenantPlan,
  NewTenantPlan,
  Admin,
  NewAdmin,
} from "./schema-platform";

// Customer schema (operational data)
export {
  customerSchema,
  tenants,
  tenantPeopleFields,
  people,
  tenantPeopleFieldValues,
  tenantHelpers,
  tenantUsers,
  tenantTeams,
  tenantTeamMembers,
  tenantTeamSkills,
  tenantTeamMemberSkills,
  tenantSkillIncompatibility,
  tenantEventTemplates,
  tenantEventTemplateSlots,
  tenantEvents,
  tenantEventSlots,
  tenantEventAssignments,
  tenantsRelations,
  tenantPeopleFieldsRelations,
  peopleRelations,
  tenantPeopleFieldValuesRelations,
  tenantHelpersRelations,
  tenantUsersRelations,
  tenantTeamsRelations,
  tenantTeamMembersRelations,
  tenantTeamSkillsRelations,
  tenantTeamMemberSkillsRelations,
  tenantSkillIncompatibilityRelations,
  tenantEventTemplatesRelations,
  tenantEventTemplateSlotsRelations,
  tenantEventsRelations,
  tenantEventSlotsRelations,
  tenantEventAssignmentsRelations,
} from "./schema-customer";

export type {
  Tenant,
  NewTenant,
  TenantPeopleField,
  NewTenantPeopleField,
  Person,
  NewPerson,
  TenantPeopleFieldValue,
  NewTenantPeopleFieldValue,
  TenantHelper,
  NewTenantHelper,
  TenantUser,
  NewTenantUser,
  TenantTeam,
  NewTenantTeam,
  TenantTeamMember,
  NewTenantTeamMember,
  TenantTeamSkill,
  NewTenantTeamSkill,
  TenantTeamMemberSkill,
  NewTenantTeamMemberSkill,
  TenantSkillIncompatibility,
  NewTenantSkillIncompatibility,
  TenantEventTemplate,
  NewTenantEventTemplate,
  TenantEventTemplateSlot,
  NewTenantEventTemplateSlot,
  TenantEvent,
  NewTenantEvent,
  TenantEventSlot,
  NewTenantEventSlot,
  TenantEventAssignment,
  NewTenantEventAssignment,
} from "./schema-customer";
